version: "3"

services:
  f4w_logger_proccessing:
    build: .
    image: f4w/logger_proccessing
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.23.0.6:514"
    restart: always
    networks:
      - default